name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js (if your project uses Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Change this to your Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Build website
        run: |
          npm run build  # Change this if you use a different build tool

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          npm test  # Modify if you use a different testing tool

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy to production
        run: |
          # Add deployment commands here
